### ISSUE TITLE
Trouble with ssh-copy-id

### ISSUE THREAD

**Issue by jh197033** [Bill-Stewart/CygSSH#1]
I have the cygSSH setup and running on Windows Server 2016 and I can ssh into the server from my iMac Pro terminal with:

ssh administrator@111.111.111.111 

which then asks me for my admin password all is ok, I am presented with "PS C:\Users\Administrator>". My problem is I am trying to use the ssh_copy_id command to send up my key with the following command:

ssh-copy-id -i ~/.ssh/id_rsa.pub administrator@111.111.111.111

it prompts me for my password which I enter but then get the following error:

dash: 1: exec: sh: not found

What am I doing wrong?

I also followed the following guide online to manually add the key but I am still presented with my password prompt when I try and shh

scp ~/.ssh/id_rsa.pub user@remote.example.com:/tmp/id_rsa.pub
ssh user@remote.example.com 
cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys

taken from https://unix.stackexchange.com/questions/29386/how-do-you-copy-the-public-key-to-a-ssh-server

Regards

James

**Comment by Bill-Stewart** [comment]
The `ssh-copy-id` script makes some assumptions about the server installed using the CygSSH package that are not valid:

- There is no `sh` shell installed
- The `chmod` command will not work

To configure a public key logon for SSH, follow the "Using Public Key Authentication" section in the User Guide.
